# Generated by Django 3.2.4 on 2021-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_maid_register_maid_registerm'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('contactnumber', models.CharField(max_length=200)),
                ('fees', models.CharField(max_length=200)),
            ],
        ),
    ]
